---
- name: setup ceph compute node
  hosts: ceph-compute
  become: true
  tasks:
    - name: Configure firewall rules
    - firewalld:
        port: 6800-7300/tcp
        zone: public
        permanent: yes
        state: enabled
    - name: End of setup
      command: /usr/bin/true
      register: ceph_compute_node_done
      ignore_errors: True
